### ISSUE TITLE
nothing happens when I open the .exe

### ISSUE THREAD

**Issue by panicvictor** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#10]
when i run the .exe it opens and closes immediately

**Comment by Tom60chat** [comment]
Hello,
Can you tell me what OS you are on?

**Comment by panicvictor** [comment]
Windows 10 64Bits AMD

**Comment by Tom60chat** [comment]
It is very likely that the Settings.json file was badly written.

Make sure the Settings.json file looks like this:
```json
{
  "Accounts": [{
      "Username": "you@domain.com",
      "Password": "yourPassword"
    },{
      "Username": "you2@domain.com",
      "Password": "your2Password"
    }]
}
```

You can put your file on a website like https://jsonchecker.com/ to verify that it's valid (without the passwords, just in case)

**Comment by Tom60chat** [comment]
The new [0.7 release](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/0.7) might help you, you should try it.

**Comment by panicvictor** [comment]
Continues closing immediately after running, I used the site to check the json file and there is nothing wrong with it

**Comment by Tom60chat** [comment]
Is it possibe you can take a screenshot of windows before it closes?

**Comment by panicvictor** [comment]
There's no time to take a screenshot, so I made a video:

Uploading 2022-03-06 21-19-33_Trim (2).mp4…

**Comment by panicvictor** [comment]
There's no time to take a screenshot, so I made a video: https://www.youtube.com/watch?v=r7wfugTF1i4

**Comment by Tom60chat** [comment]
Thank you for your time, and for the video.

Is it possible that you show the error from windows event viewer ?


To do this open event viewer by doing: Win + R then type "eventvwr" finally click on OK  (1)
Then go to Windows Logs(2) > Application(3).
Next look for an error that corresponds to the Microsoft Rewards Farmer.exe application (4)
Finally take a screenshot and send it here.


![image](https://user-images.githubusercontent.com/25564492/157017815-927f44ce-2030-4aa6-8cee-c6c50c8e0b2a.png)

**Comment by Tom60chat** [comment]
Hey, I just remembered that the package doesn't come with .NET Core, maybe all you have to do is install .NET 3.1 for v0.7.0 and before (or .NET 6 for v0.7.1 and later versions)

[Download .NET Core 3.1](https://dotnet.microsoft.com/en-us/download/dotnet/3.1/runtime)
[Download .NET Core 6](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime)
