### ISSUE TITLE
 how to generate log file

### ISSUE THREAD

**Issue by kuramadur30X** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#109]
How can I generate the log file in this new version of the script?

**Comment by Tom60chat** [comment]
Normally you have to put the file loggers like that :

```
{
  "Accounts": [
    {
        ...
    }
  ],
  "Loggers": {
    "Files": [
      {
        "URI": "./Logs",
        "Levels": [
          "Log",
          "Exception",
          "Summary"
        ]
      }
    ]
  }
}
```

**Comment by kuramadur30X** [comment]
Does this have to be added account by account or do you have to put it at the end of everything?

**Comment by Tom60chat** [comment]
At the end of everythings

**Comment by kuramadur30X** [comment]
the log is no longer generated in a single file?
because I use a spreadsheet for control and generating it in a single file is simpler.

**Comment by Tom60chat** [comment]
> the log is no longer generated in a single file?

The version 0.10.1 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.1-beta1
