### ISSUE TITLE
Misssing Settings.json file

### ISSUE THREAD

**Issue by DerMuffin** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#11]
Cant get the exe to run because everytime i try its get this error.

The json file only have one account. i replace the default Mail and password.

.NET 6 and 3.1 is installed

use your latest version of the exe

Windows 10 64 Bit

**Comment by DerMuffin** [comment]
I try to start the exe with powershell and by double clicking it
The Settings.json is in the same directory (Just downloaded the releases)
Its on the C Drive (Downloads Folder)

and by the way. Your "All" Release does work fine. But the x64/x86 does have this issue

**Comment by Tom60chat** [comment]
It's strange, good to know that the "All" version works well.
I believe this issue is fixed in the next version.

I consider this issue solved (and I will remove the x64/x86 version)
