### ISSUE TITLE
Tui gets stuck on card processing even though it is doing searching task and I am gaining points

### ISSUE THREAD

**Issue by CrazyLight21** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#112]
[2023-03-15 14.47.21.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10998304/2023-03-15.14.47.21.txt)
Sometimes the program tui gets stuck at card processing even though it is searching something.

**Comment by benschi11** [comment]
I have the same problem. Stuck in '(3/6) Getting Cards...".
[2023-03-17 09.24.44.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10999388/2023-03-17.09.24.44.txt)

**Comment by Tom60chat** [comment]
Oh wait, is the app graphically stuck, it's just a visual bug?

**Comment by CrazyLight21** [comment]
yes

**Comment by CrazyLight21** [comment]
Now, I've got another bug. Most of the time I open the program this pops up. Is there any solutions to this?
![image_2023-03-18_132047036](https://user-images.githubusercontent.com/128027767/226092849-9d4db991-d632-4e3f-8c0c-b18d701c689c.png)

**Comment by Tom60chat** [comment]
> Now, I've got another bug. Most of the time I open the program this pops up. Is there any solutions to this? 

Check #119

**Comment by Tom60chat** [comment]
Well, if this is just a visual bug, it's a minor issue.

I probably now why this is happening, he will be fixed but with low priority.

**Comment by CrazyLight21** [comment]
> Well, if this is just a visual bug, it's a minor issue.
> 
> I probably now why this is happening, he will be fixed but with low priority
Thanks!

**Comment by CrazyLight21** [comment]
The bug is a visual bug and it will be fixed maybe in the next update.
