### ISSUE TITLE
Cant add more than one Account

### ISSUE THREAD

**Issue by DerMuffin** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#12]
For some reaseon the exe file only reads the last entry in the json file.

Could you provide a correct json File for multiple accounts?

**Comment by Tom60chat** [comment]
Here is an example of Settings.json for multiple accounts:

```json
{
  "Accounts": [{
      "Username": "yourAccount1@mail.fr",
      "Password": "awesomePassword"
    },
    {
      "Username": "yourAccount1@mail.fr",
      "Password": "veryAwesomePassword"
    }]
}
```

I will add this example in the README for future users who are not familiar with the json language
