### ISSUE TITLE
New version test results

### ISSUE THREAD

**Issue by hack003** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#121]
New version test results

The invitation link is available at https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp.
I found a strange problem, directly open run will crash back, will prompt an error such as picture  (1) right-click to run as administrator, can run normally, the diplay has been initializing, then 5 minutes will show timeout(2), the test version is 0.10.1
Log is (3)
(1)
![image](https://user-images.githubusercontent.com/47956951/226076928-c8b219bb-ac0b-4590-a8c0-cadb12dbf892.png)

(2)
![image](https://user-images.githubusercontent.com/47956951/226077015-fa741433-fb11-45d5-9b3c-b06f6c40c6e5.png)

(3)
[2023-03-18 09.43.01.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/11007225/2023-03-18.09.43.01.txt)

**Comment by Tom60chat** [comment]
1: #119 
2: #104
