### ISSUE TITLE
Farm, open a free VPN, farm again and close VPN

### ISSUE THREAD

**Issue by riahc3** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#123]
Hello

From what it seems, it possible to farm from two different locations per day to double the farming.

It would be nice to integrate this automatically some way. ProtonVPN comes to mind as being free.

Thank you

**Comment by Tom60chat** [comment]
See #92 

VPN automation it's not possible.

If you can, I recommend to use an external script. (Because I don't want to have to implement every VPN soft on earth)

**Comment by Lehoooo** [comment]
maybe consider building as a docker container, then you can link a virtual network like gluetun (https://github.com/qdm12/gluetun)
