### ISSUE TITLE
When I run on window7, I get the following error and stop running.

### ISSUE THREAD

**Issue by BigYty** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#128]
![image](https://user-images.githubusercontent.com/35890111/226831357-2525945d-67a4-4c67-9ea8-7f9f62fc23c0.png)

**Comment by CrazyLight21** [comment]
almost everyone is getting the same problem Even on win 10 32bit it still dosent work check
it is a dup of #119 btw
