### ISSUE TITLE
App closes itself after initialization

### ISSUE THREAD

**Issue by AdicoS99** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#129]
I am completely oblivious to programming stuff etc.. so I have no clue what the problem might be but whenever I open the app this pops up

![image](https://user-images.githubusercontent.com/36305058/226843773-3ce600ae-5251-442f-b7b4-aab0195006a5.png)

And after that the app just closes itself.

**Comment by baff3r** [comment]
same error

**Comment by CrazyLight21** [comment]
> I am completely oblivious to programming stuff etc.. so I have no clue what the problem might be but whenever I open the app this pops up
> 
> ![image](https://user-images.githubusercontent.com/36305058/226843773-3ce600ae-5251-442f-b7b4-aab0195006a5.png)
> 
> And after that the app just closes itself.

dup of #119

**Comment by Tom60chat** [comment]
@CrazyLight21 Indeed, duplicate of #119.
