### ISSUE TITLE
Dont collect all Points/cards

### ISSUE THREAD

**Issue by DerMuffin** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#13]
I do have a setup of 5 Accounts running your "All" Version of the script.

It complete without any errors. But when i look in my Rewards Dashboard, some cards are missing.

Maybe some URLs changed?

If you need any futher information dont hesitate to contact me.

Thanks!

**Comment by Tom60chat** [comment]
Hello,

I am actually aware that not all points are farmed.

That's what I'm trying to solve (Don't hope it gets solved soon)

**Comment by Tom60chat** [comment]
It should be improved in [version 0.8.0](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.8.0)
