### ISSUE TITLE
How do I use it on centos?

### ISSUE THREAD

**Issue by Sentaku1129** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#136]
What do I do if I want to use it on centos?

**Comment by haq** [comment]
You can try the release build, if that doesn't work you can try building the app yourself.

**Comment by Sentaku1129** [comment]
does this acquire me to compile source code？linux-x64 of release can't use it directly？

**Comment by haq** [comment]
Try running `linux-x64` to see if it works.

**Comment by Sentaku1129** [comment]
> Try running `linux-x64` to see if it works.

All files are pdb files, how do I run them?

**Comment by Tom60chat** [comment]
Don't want to be mean, but can you learn how to use linux, before opening an issue?
We are not tech support for global computer issue, just MRF.

Any way start this app:
![image](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/assets/25564492/3d9478cf-33bc-403b-b938-b7ff8253e906)
Do chmod +X if needed, and don't forgot to install dotnet 6.
