### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by pan8664716** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#143]
Dear Tom:

I have downloaded the source code of v0.10.1-beta1 and v0.10.1, but I encountered errors when compiling them by running build.bat. However, the source code of v0.9.3-beta1 can be compiled successfully.

I am using Jetbrains Rider IDE, and I can debug the source code of v0.10.1-beta1 and v0.10.1 without issues, but I still encounter errors when compiling them.

Here is the error message, could you please help me take a look and suggest a solution?

`EXEC : error : Artifact does not exist. v6.0.14/win-x64 [E:\code\mrf\Microsoft Rewards Farmer.TUI\Microsoft Rewards Far
mer.TUI.csproj]
C:\Users\pan86\.nuget\packages\nulastudio.netcorebeauty\1.2.9.3\targets\Beauty.targets(35,5): error MSB3073: 命令“"C:\Use
rs\pan86\.nuget\packages\nulastudio.netcorebeauty\1.2.9.3\targets\../tools/win-x86/ncbeauty.exe"        "E:\code\mrf\Mi
crosoft Rewards Farmer.TUI\bin\Release\net6.0\publish\win-x64\/." libraries ”已退出，代码为 1。 [E:\code\mrf\Microsoft Rewards
Farmer.TUI\Microsoft Rewards Farmer.TUI.csproj]`
@Tom60chat

**Comment by Tom60chat** [comment]
Hum, no idea.

Maybe somethings it's wrong with your install of VS code (I use the 2022 one), or dotnet, or maybe clean the projet and retry.
All I can say is that he does not like [NetBeauty 2](https://github.com/nulastudio/NetBeauty2).
