### ISSUE TITLE
When hanging to the Hong Kong region, it seems that the points of the other region cannot be obtained

### ISSUE THREAD

**Issue by righted** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#151]
Original title: 当挂到香港地区的时候 似乎获取不了另一个地区的积分

![image](https://user-images.githubusercontent.com/66148581/230765108-e5ed133a-6aa0-48d8-a958-e2e2ac80bd69.png)

**Comment by righted** [comment]
但是我就只是弄香港和国区的&nbsp;第二天挂在香港的时候可以，这种时候挂国区就不行，反正就只能二选一。是不是因为不同地区积分获取的时间刷新时间不同？我看帐号每日获得积分是大于165的




老鬼喝小酒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tom60chat/Microsoft-Rewards-Farmer-Sharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 中午1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tom60chat/Microsoft-Rewards-Farmer-Sharp] 当挂到香港地区的时候 似乎获取不了另一个地区的积分 (Issue #151)





 
因该是微软的限制，现在好像有国区记录的情况下最多只能拿两个区的积分（含国区）

**Comment by GeorgeDong32** [comment]
有可能是时间的问题，不过更建议用 -nh 参数看看浏览器界面，有些时候访问国区Rewards的时候会卡住

**Comment by pan8664716** [comment]
在24小时内，你仅可以使用两个国家或地区的IP来进行获取积分，比如你早晨8点使用了大陆的IP，而12点使用了香港的IP，那当天您只可以通过大陆和香港地区进行获取积分，如果你在15点又使用美国IP来进行积分获取是失败的，需要等到第二天才可以更换ip

**Comment by Tom60chat** [comment]
Thanks to everyone who helped @righted
There has been no response after over a month, so I assume the problem has been resolved.
If not, feel free to reopen the issue.

Trans (DeepL): 感谢每一位帮助过我的人@righted
一个多月后还没有回应，所以我认为问题已经解决了。
如果没有，请随时重启该问题。

**Comment by yukiryo** [comment]
I haven't earned points for several days and still can't earn in my country
