### ISSUE TITLE
如何全自动运行这个脚本

### ISSUE THREAD

**Issue by wangzhao1124** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#155]
For qestion, please visit the Discord server.

The invitation link is available at https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp.
我想知道应该如何在GitHub的action中使用该脚本进行全自动化运行，并且是定时的

**Comment by Tom60chat** [comment]
我知道，我知道GitHub的行动不是为了这个。 (DeepL trad)
