### ISSUE TITLE
Chromium in background

### ISSUE THREAD

**Issue by Cucklord420** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#16]
When I run the exe in headless mode after it completes everything it leaves open a bunch of chromium processes in the background and has to be manually closed in task manager

**Comment by Tom60chat** [comment]
Yes, I may have forgotten to clean the browsers at the end of the execution of the application in headless.

**Comment by Tom60chat** [comment]
After some testing, this happens if the app is closed without pressing any key at the end, which prevents it from cleaning up in time.

**Comment by Tom60chat** [comment]
Should have been fixed in [version 0.8.0](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.8.0)
