### ISSUE TITLE
Unable to complete the search task on the mobile end

### ISSUE THREAD

**Issue by YiGang-Grapefruit** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#160]
After running the program, other search tasks can be completed, but the mobile search task cannot be completed at all times
![image](https://user-images.githubusercontent.com/63415204/234650171-c4c6c33c-18a8-47ad-808d-7069e19410a8.png)

**Comment by cqjerry** [comment]
same problem

**Comment by CN-Patrick** [comment]
i have same problem,

**Comment by windskyxb** [comment]
Similarly, I also have the same problem

**Comment by DarkEnergy666** [comment]
See issue# 110 [one of the last post]
This should fix the problem.

**Comment by windskyxb** [comment]
> See issue# 110 [one of the last post] This should fix the problem.

Following this method of operation, it initially returned to normal, but after a few days, this problem will reappear

**Comment by Tom60chat** [comment]
Duplicate of #110
