### ISSUE TITLE
Microsoft Rewards has changed its rules for earning points？

### ISSUE THREAD

**Issue by pan8664716** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#165]
Microsoft Rewards has changed its rules for earning points？ you can only earn points from one region. After switching IP through VPN, it is no longer possible to earn points.

**Comment by wangzhao1124** [comment]
I think so, and I can't brush up all the points after using VPN

**Comment by Tom60chat** [comment]
Look like #151
