### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by Affoghiamoci** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#2]
how do i start it from macos?

**Comment by Tom60chat** [comment]
Hello, I haven't tested the app for macOS, but it should work.
I don't know much about macOS, but I think you need to open Terminal and navigate to the Microsoft Rewars Farmer Sharp folder that you extracted with `cd` and just run the app by doing `./Microsoft\ Rewards\ Farmer.exe`

**Comment by Tom60chat** [comment]
Hello, I haven't heard back from you, I consider your problem is solved.
