### ISSUE TITLE
how to use Arguments?

### ISSUE THREAD

**Issue by namimama** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#23]
i know has a tutorial in the description but is complex, when i open the program i can't type nothin, how can i use the arguments?

**Comment by Tom60chat** [comment]
- Open the CMD
- [Red] **C**hange **D**irectory (cd) where the app is
- [Green and Yellow] And start the application with the arguments

![image](https://user-images.githubusercontent.com/25564492/202751081-b135d5f3-354b-437e-bd52-07083355389d.png)

You can do the same things with a shortcut or a script file.

**Comment by Tom60chat** [comment]
I haven't received any answer for more than a week, I consider the issue is resolved.
