### ISSUE TITLE
Error 0.82

### ISSUE THREAD

**Issue by fabiovieitas** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#24]
Good afternoon. Used version 0.71 flawlessly. I changed to version 0.82 and it doesn't farm.
![Screenshot_8](https://user-images.githubusercontent.com/73303693/202745116-262964da-4a7a-4773-85ff-b7794a639aaf.png)

**Comment by Tom60chat** [comment]
Hello,
Thanks for the feedback.

That weird, can you give me the last log file in ...\Microsoft Rewards Farmer\Logs?

**Comment by fabiovieitas** [comment]
[2022-11-18 12.42.43.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10042955/2022-11-18.12.42.43.txt)

**Comment by Tom60chat** [comment]
Yes, with this kind of limited information, I can't figure out what really happened.

But I notice that the application didn't try to do a desktop search.

I'll investigate on my end to try to reproduce the error, when I have some time.

**Comment by fabiovieitas** [comment]
Version 0.71 is perfect.

Tomorrow I will test version 0.8.

**Comment by fabiovieitas** [comment]
Good afternoon. I just tested version 8.0 and it didn't work either...

I'll stick to version 0.71 which is perfect!

**Comment by Purkeez** [comment]
hey i cant find the exe file in the folder. Where can i find it exactly?

**Comment by Tom60chat** [comment]
Hello @fabiovieitas,

I am glad to share with you the new version of MRF:
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.0

I hope I could solve most of the issues.

If the issue was fixed in your side, feel free to close the issue.

**Comment by Tom60chat** [comment]
#31
