### ISSUE TITLE
How to run on Linux

### ISSUE THREAD

**Issue by DerMuffin** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#26]
Hey,

since linux doesnt have any Exe File... How to run the script there?

Thanks

**Comment by Tom60chat** [comment]
Hello,
Have you use the linux package ?

**Comment by DerMuffin** [comment]
Yes. For x64.

Is there any file that i need to make exexutable? Which one of theese Files are the actual rewards Script?

**Comment by Tom60chat** [comment]
The "Microsoft Rewards Farmer" file is the executable.
You might have to.make it executable

**Comment by Tom60chat** [comment]
Hello back, @DerMuffin 

I have not received any answer from you, I consider that this problem has been solved.
