### ISSUE TITLE
[Question] How much do you get per day?

### ISSUE THREAD

**Issue by webdesignschool** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#30]
Does this only do searches or does it also do other tasks?
How much is made per day/how long does it take?

**Comment by Tom60chat** [comment]
Search and cards resolve.
230~points per day

**Comment by namimama** [comment]
i make a 600+ per day with VPN

**Comment by Tom60chat** [comment]
Didn't know that

**Comment by namimama** [comment]
> Didn't know that

it's possible, u can farm frist in your country, then u use a vpn to EUA.

**Comment by Tom60chat** [comment]
@namimama  I confirm, the VPN technique works well!

@webdesignschool do we have answer your question ?
If I don't get an answer the issue will be closed in 5 days.

**Comment by namimama** [comment]
> @namimama I confirm, the VPN technique works well!
> 
> @webdesignschool do we have answer your question ? If I don't get an answer the issue will be closed in 5 days.

Nice my man, u are the best.
