### ISSUE TITLE
version 0.91 with the same errors... 

### ISSUE THREAD

**Issue by fabiovieitas** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#34]
Unfortunately the same error as the previous version.

Run the script 2x and it still only gives 130 out of 150 points.
![Pontos](https://user-images.githubusercontent.com/73303693/206925400-b0546ad7-ae1e-4f43-ac88-e5e4d8905ff3.png)

He has to do 30 searches on the PC. You're only turning 16...

OBs.: BRAZIL!

**Comment by Tom60chat** [comment]
As I said, there is no hard written value in the program, and if it did, it would do 30 like you.

I'm starting to be clueless as to why it's not working as expected.

I can blame network speed and stability, I have fiber on my end but even so, there is some variable on your end that I can't replicate on my end.

**Comment by fabiovieitas** [comment]
Tom, I have 13 accounts. I use the script in 2 parts (6 and 7). Before version 7.0 it ran perfectly. After microsoft modified the system, all my accounts give the same end result.

Acer Aspire 7
8gb ram
600mb internet

**Comment by Tom60chat** [comment]
One solution I can think of is to manually tell the program how many searches it should do.

**Comment by Tom60chat** [comment]
Oh no I did find why
![image](https://user-images.githubusercontent.com/25564492/207003114-47daf624-8fb0-4907-991d-b839b520157c.png)
In France, the first column is the mobile search while in your country, it is the PC search

So the application to reverse the mobile search number with the PC search number.

**Comment by fabiovieitas** [comment]
Ready. Error found!!!!

**Comment by Tom60chat** [comment]
Hello, during this week or the next week. 🤷‍♂️

**Comment by fabiovieitas** [comment]
> 

Thank you very much!!! Your script helps a lot!!!!

**Comment by Tom60chat** [comment]
Hello back,

The version [0.9.2-beta1](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.2-beta1) has been release.

Let me know if your issue has been fixed.

**Comment by AdicoS99** [comment]
> Hello back,
> 
> The version [0.9.2-beta1](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.2-beta1) has been release.
> 
> Let me know if your issue has been fixed.

I used to have the same problem as fabiovieitas, I ran the script AFTER using the 0.91 and it gave me 42 points, which is exactly what was missing from the desktop researches, so it's safe to assume the problem has been solved (at least for Italy) but I'll give more precise informations tomorrow! Thank you for your work!

**Comment by fabiovieitas** [comment]
> Hello back,
> 
> The version [0.9.2-beta1](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.2-beta1) has been release.
> 
> Let me know if your issue has been fixed.



Perfect!!! Everything working!!!

Thanks a lot!!!!

**Comment by Tom60chat** [comment]
I am glad to hear that your problem has been solved.

I'm closing the issue.
