### ISSUE TITLE
App can not get the point amount so infinite Searches

### ISSUE THREAD

**Issue by gent00** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#37]
![image](https://user-images.githubusercontent.com/5721191/208237733-62d1b635-cd86-4099-b3db-85252025f0d4.png)

I have 1000mbit connection.  Running in Win 11.

This part is infinite.

**Comment by gent00** [comment]
anyways i closed the app and opened again and it works. Maybe first time issue.

**Comment by Tom60chat** [comment]
Well, now that I think about it that might be a problem, I think I made a mistake in the code.

**Comment by Tom60chat** [comment]
Should have been fixed on v0.9.3
