### ISSUE TITLE
Completing cards over and over again

### ISSUE THREAD

**Issue by throwaway45632** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#38]
I am in the United States and I'm using 0.9.1, after it completes the cards it keeps repeating it around 2-3 times, so the process takes much longer than before.

**Comment by Tom60chat** [comment]
Hello, can you try the version 0.9.2 ?

**Comment by throwaway45632** [comment]
It's still the same, Card processing 1/5 2/5 0/5 1/5 2/5 1/5 etc

**Comment by Tom60chat** [comment]
The new version 0.9.3 has been released.

Please test it and leave a comment if your problem has been solved or not.

[Download link](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.3-beta1)

**Comment by Tom60chat** [comment]
This issue was maybe linked to #49

**Comment by throwaway45632** [comment]
Still the same, after Card processing 4/4 it goes back to 1/4, it completes Card processing two times, then it does Card processing for the 3rd time. It's not a deal breaker or anything but it's still happening

**Comment by Tom60chat** [comment]
Given what you told me it's the same problem as #49, I close this one and I invite you to continue the discussion on #49.
