### ISSUE TITLE
is there any way to reduce the use of GPU

### ISSUE THREAD

**Issue by namimama** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#39]
my GPU is running at 100% with the browser hidden, i'm only using 6 accounts

**Comment by Tom60chat** [comment]
Are your GPU 100% because of the app or the chromes instance ?

**Comment by namimama** [comment]
all Chromium processes are pulling too much.

**Comment by Tom60chat** [comment]
Well I can't do anythings for that, that how chromium work 🤷‍♂️.

You can use the farm limiter argument to reduce the ammount of chromium processes.

**Comment by Tom60chat** [comment]
Maybe, with some launch argument for chrome we might get some optimisation.

**Comment by namimama** [comment]
i got it, thanks ma boy, u r the best. I am limiting the number of accounts, but it is very slow.

**Comment by Tom60chat** [comment]
I'm closing this because the suggestion has been forwarded to the Discord server : https://discord.com/channels/1066284573194989629/1066302943470571541
