### ISSUE TITLE
[Feature request] I’d like to request for a few basic features 

### ISSUE THREAD

**Issue by kaiser62** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#41]
Hi,
Thanks for your wonderful work, this has been a great help for farming Overwatch Coins. Kudos to you. Although the program is running fine, I’d like to request for a few small features : 

1. Farm Cards or Searches Only.
2. Keep a log of all points farmed with email account in a log file.
3. Manually select an account which would be very helpful for testing stuff.
4. Very Very Optional, but it’d be great to have a way to integrate discord webhooks or telegram bots with the program log.

Thank you again for this wonderful program.

**Comment by Tom60chat** [comment]
Hello, thanks for your feedback.

I would like to know more why you want those feature, if you have some exemple.
For the 2. You already have a log file, but I understand you want a log file that only give result ?

**Comment by kaiser62** [comment]
Hello, 

For the reason of number one, when using vpn, in certain countries sometimes you can't farm cards at all or you can't farm searches at all, so if there was an option to actually select Cards or searches, it'd save much time.

For no. 2, The current log file does not write the account names, just writes down a number instead of an account name, so it's hard to distinguish between accounts, if you can implement names with the current log file, it would be enough for me.

For no. 3, Getting to select a single account would be helpful because sometimes, it might crash on one account but farm other accounts. Then if I had the option to select that single account, it'd be very helpful.

No. 4 is completely optional, We don't need it but its good to have feature. 

Also I had a question, what does "-b" do? what did you mean by batch mode?

**Comment by kaiser62** [comment]
Hello,
I found this [supersonic quiz solver](https://gist.github.com/dmn001/d6eb2ccb69a767e9fa79e28bfd9cee34#file-bing-rewards-supersonic-quiz-clicker-user-js), maybe you could implement this in your code. It works and works efficiently.

**Comment by kaiser62** [comment]
Hi @Tom60chat,

Thanks for listening to my suggestions, the script I mentioned was only for the supersonic quizzes only (the quizzes with 5 answers out of 7) , albeit that does not save too much time, but it does identify and select only right answers which could save a bit of time.

And thanks again for listening to the suggestions, you have made an awesome program.

Regards.

**Comment by kaiser62** [comment]
Hello @Tom60chat Brother,

I have found another python script which solves quizzes with only right options, both for 4 and 8 options, could you look at [this](https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/master/ms_rewards_farmer.py#L871#L913) please? 

Credits : charlesbel and farshadz1997

**Comment by Tom60chat** [comment]
After a few tries, it allows to get a better completion speed.
Thanks for the sharing, this will be implemented.

**Comment by Tom60chat** [comment]
Hello, again.

1. Your suggestion has been transferred to the Discord server.
2. #54
3. Implemented for next version
4. Your suggestion has been transferred to the Discord server and the implementation might appear on the next version.

To make it simple, the suggestions are transferred to the discord server, you can follow the progress there 😉
