### ISSUE TITLE
Index was outside the bounds of the array　error

### ISSUE THREAD

**Issue by syunohito** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#44]
![image](https://user-images.githubusercontent.com/72976164/210146147-867d9781-7be5-4b6c-b7ac-e375ce410ef0.png)

**Comment by Tom60chat** [comment]
Well, Bing did something that have broke the app again.

This is major bug, and will be fixed asap.

**Comment by syunohito** [comment]
![image](https://user-images.githubusercontent.com/72976164/210189941-5a56814c-b930-4edb-9ed6-29ee345451bf.jpeg) Also, my account was banned the moment I redeemed the 600 yen Amazon gift certificate!
I have redeemed 4 times so far and all have been banned!

**Comment by Tom60chat** [comment]
@syunohito please open a new isue for a different one.

**Comment by kuramadur30X** [comment]
version 0.9.1 is running, but it is not doing all the searches of the day.

**Comment by Tom60chat** [comment]
@kuramadur30X have you having the Index was outside the bounds of the array issue ?

**Comment by Tom60chat** [comment]
The new version 0.9.3 has been released.

Please test it and leave a comment if your problem has been solved or not.

[Download link](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.3-beta1)

**Comment by kuramadur30X** [comment]
apparently it is operating normally

Tks


________________________________

**Comment by Tom60chat** [comment]
I'm closing the issue, feel free to open it if the issue persists
