### ISSUE TITLE
Getting cards or signing in for more than an hour.

### ISSUE THREAD

**Issue by VanMeh** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#48]
I tried different versions (9.2, 9.1) and either the app freezes on signing in and hothing happens or on getting cards. Before that I was getting "Index was outside the bounds of the array" but as I understood its gonna be patched in the next verison.

**Comment by Tom60chat** [comment]
Maybe, wait for new version to know if this is related to other know issue.

**Comment by Tom60chat** [comment]
The new version 0.9.3 has been released.

Please test it and leave a comment if your problem has been solved or not.

[Download link](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.3-beta1)

**Comment by VanMeh** [comment]
Installed the new one but it still doesn't go through getting cards part. I will probably try a new account and see if it works.

**Comment by VanMeh** [comment]
Ok, it works now and I think I've found a problem. Apparently, once about a month since account registration has passed Microsoft forces you to add a reserver email and a special page loads on every login thus the app couldn't reach the page with cards and as this page was not an error MRFS didn't know what to do and kept on trying.

**Comment by Tom60chat** [comment]
Hum, normally when those kind of things append MRF, warn the user and avoid to keep trying.
Maybe I forgot to implement for this special case.

This need some investigation.

**Comment by VanMeh** [comment]
Also I just noticed that for some reason it skips the bottom row of cards (At least on English vpn). Same on all 5 accounts I have.

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Tom60chat** [comment]
For cleaning reasons, I will close this issue now, do not hesitate to reopen if the same issue comes back.
