### ISSUE TITLE
Doesn't load on one account gives error

### ISSUE THREAD

**Issue by Cucklord420** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#52]
On one of my accounts it constantly gives this error: [Exception] Farmer - Object reference not set to an instance of an
object. 
When I start it in not headless mode so I can see what the problem is, it instantly closes the browser so I don't know what the problem is. I can login to the account just fine.

**Comment by Tom60chat** [comment]
Can you give me the last log file in the logs folder, please ?

**Comment by Cucklord420** [comment]
[2023-01-07 13.38.17.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10367392/2023-01-07.13.38.17.txt)
Heres the most recent log file

**Comment by Tom60chat** [comment]
Ok, the error was because if the cookie file was corrupt or invalid, the RestoreAsync function would fail.

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Cucklord420** [comment]
Tried it out, but it caused more problems with multiple accounts not working.
![issues](https://user-images.githubusercontent.com/48045150/225186533-6a9e7d83-e63d-4038-a7f3-785a7d5b45f9.png)

**Comment by Tom60chat** [comment]
@Cucklord420 I think the this issue is solved, please see #67 for your current issue.

I am closing this issue, feel free to reopen it if necessary.
