### ISSUE TITLE
Suggestion: Scheduled start and discord server

### ISSUE THREAD

**Issue by darzex** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#53]
hi
is it possible to loop it for everyday so at like 10am it run all make point and the next day at 10am again again so i can let a linux pc for ever without doing something lol
and u should create a discord server :)

**Comment by Tom60chat** [comment]
Hello,
1. This is called a cron job :
   - https://www.freecodecamp.org/news/cron-jobs-in-linux/
   - https://www.hostinger.com/tutorials/cron-job
 
2. Technically there is a discussions tab on this project  : https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/discussions
  And frankly I might not be able to manage a server, already I'm overloaded by the development of the project, so apart from making one and letting anarchy reign, I'm not sure it's a good idea.

**Comment by Tom60chat** [comment]
It's been two weeks, I consider that my answer satisfied you.

You can continue the discussion on the Discord server.
