### ISSUE TITLE
Suggestion: Generate log file in spreadsheet format

### ISSUE THREAD

**Issue by fabiovieitas** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#54]
suggestion. Generate a log file in xls so that we can better control the points.

Tank you

**Comment by Tom60chat** [comment]
XLS is proprietary format for Microsoft Excel, CSV can do the same things and it's not proprietary.

Don't really understand by "better control the points"?

**Comment by kuramadur30X** [comment]
> sugestão. Gere um arquivo de log em xls para que possamos controlar melhor os pontos.
> 
> Tanque você
it is not necessary to generate it in xls, with the txt file itself if you put it in a spreadsheet it is possible to get data and then do procv. I did this in my control sheet.

**Comment by kuramadur30X** [comment]
> sugestão. Gere um arquivo de log em xls para que possamos controlar melhor os pontos.
> 
> Tanque você

![IMG-20230114-WA0118](https://user-images.githubusercontent.com/121198725/212520413-8295e6b5-55ef-45f4-b955-6fdf160b40c5.jpg)

**Comment by Tom60chat** [comment]
I don't really understand what it's for, but do you do statistics or something else?

**Comment by kuramadur30X** [comment]
only to control the number of points, and to know when it is already possible to redeem the account.

but I do statistics, conversion of the amount of points to local currency etc...

**Comment by Tom60chat** [comment]
Interesting, I'll see if I can do anything to make it easier.

**Comment by Tom60chat** [comment]
The suggestion has been imported on the Discord channel : https://discord.com/channels/1066284573194989629/1066666757860896888
