### ISSUE TITLE
[Exception] `EvaluationFailedException`: Evaluation failed: ReferenceError: `_w` is not defined

### ISSUE THREAD

**Issue by VanMeh** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#55]
[2023-01-08 21.40.57.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10369225/2023-01-08.21.40.57.txt)

**Comment by throwaway45632** [comment]
I got this error the first time that I ran MRF today, then I tried version 0.9.2 and it runs fine

**Comment by kuramadur30X** [comment]
only complementing...  

here I am with the same error, it only happens when I use vpn.

No vpn in Brazil runs. 

Version 0.9.2 is operating without errors.

**Comment by AdicoS99** [comment]
[2023-01-08 16.33.56.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10380919/2023-01-08.16.33.56.txt)

Same for me

**Comment by AdicoS99** [comment]
Any news on this? Sorry to bother

**Comment by Tom60chat** [comment]
It's the weekend, so I'm working on it.
But don't expect the issue to be resolved quickly given the little time I can devote to this application.

So either I manage to fix this weekend or next weekend.

**Comment by Tom60chat** [comment]
Ok, so the problem was due to a merge conflict that didn't make to the commit and pre-release.

**Comment by Gangsh1** [comment]
same issue happened to me
but 0.9.2 works for me
0.9.3 has the issue

**Comment by link2Eps1lon** [comment]
Yes, it's weird that 0.9.3 has this issue again. Please pay attention to that.

**Comment by aayushmanmk** [comment]
Same is happening to me on 0.9.3 only when I use a vpn
[2023-03-09 16.00.52.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10930776/2023-03-09.16.00.52.txt)

**Comment by righted** [comment]
![image](https://user-images.githubusercontent.com/66148581/224530294-5d260239-3a1f-4cfa-a002-32ec50870a77.png)
0.9.3挂vpn同样出现了这样的问题

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by righted** [comment]
现在更新到最新版本已经解决-w这个问题,但是当我积分不到2级时候,这个脚本并没有作用,其他2级以上国内＋挂梯子都可以正常使用了

**Comment by Tom60chat** [comment]
Well that is another issue, if you can open one.

**Comment by Tom60chat** [comment]
For cleaning reasons, I will close this issue now, do not hesitate to reopen if the same issue comes back.
