### ISSUE TITLE
Suggestion: Use Gitter (maybe discord?)

### ISSUE THREAD

**Issue by liotwi** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#57]
Enable a chat on https://gitter.im/ for this repository.

**Comment by liotwi** [comment]
So that people can discuss about the project.

**Comment by Tom60chat** [comment]
What it's the difference between Gitter and the already enabled GitHub discussions tab?

**Comment by liotwi** [comment]
That's a another good way to exchange. Discussions can be a bit to formal. 
It is more like a Discord chatroom.
https://finddev.tools/compare/gitter/vs/github-discussions

**Comment by Tom60chat** [comment]
But if I use Discord it's kind the better of the 2?

**Comment by Tom60chat** [comment]
Well gitter is very minimal, so if people want to make suggestions, they risk getting very little visibility.
I prefer GitHub Discussion, it's a bit formal but I just have to create a chat discussion like #59 and we have about the same result as Gitter, moreover it seems simple to manage unlike Discord where we have to do everything ourselves.

**Comment by Fulasso** [comment]
We can use discord with invite only so we can share some tips like how reedem or things like that.
I have been "researching" for how to reedem lots of accounts and i would like to share some ideas.

**Comment by Tom60chat** [comment]
Even with invitation only, how can I judge that someone can be part of this private group?
And private things are against the idea of open source.

I understand the need, but the implementation can be annoying, maybe we should just use the private message at this point.

Then even if it's idea are secret, how can I implement it in the app?

**Comment by Fulasso** [comment]
> Even with invitation only, how can I judge that someone can be part of this private group? And private things are against the idea of open source.
> 
> I understand the need, but the implementation can be annoying, maybe we should just use the private message at this point.
> 
> Then even if it's idea are secret, how can I implement it in the app?

What i mean is, the project is open so keep going on that... "my" ideia of private group is what comes after using all that, because what's the point of having the tool? It's the rewards... so I'd keep this one and one just for post farming discussions

**Comment by Tom60chat** [comment]
Ok, assuming I created a discord server and created a channel just to discuss rewards privately, who would have access to this channel?

**Comment by Fulasso** [comment]
> Ok, assuming I created a discord server and created a channel just to discuss rewards privately, who would have access to this channel?

"Active" users of this project and issues forum

**Comment by Tom60chat** [comment]
Ok why not, it would be nice if a bot can automatically gave active users on the repository an active role.

**Comment by Fulasso** [comment]
> Ok why not, it would be nice if a bot can automatically gave active users on the repository an active role.

I think bots for invite is not a good ideia. You as owner of the project, did you have the numbers of download from your work? From that numbers, you can assume how many people you can invite. If the number is low, i think manual invite work better. Inside github we can't send private messages so maybe you can drop a link for like one day and how click and want get invited, i do that and maybe send a message here saying "invite closed" like a warning

**Comment by Tom60chat** [comment]
Well for v0.9.3 I got 67 download.

Yeah, I will thinks about it, my goal is that I also don't want to add more work for me

**Comment by Tom60chat** [comment]
Hello, I final create a Discord server: https://discord.gg/dA6ZTp7H4S

**Comment by Fulasso** [comment]
> Hello, I final create a Discord server: https://discord.gg/dA6ZTp7H4S

Thanks :)

**Comment by Tom60chat** [comment]
I consider the discussion is closed 😉
