### ISSUE TITLE
CheckBingReadyAsync() dead loop

### ISSUE THREAD

**Issue by fabiovieitas** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#64]
The program closes right after it runs all the activities. What can it be?

**Comment by Tom60chat** [comment]
You have out the -b arguments ?

**Comment by fabiovieitas** [comment]
NO!!!!

**Comment by Tom60chat** [comment]
I guess that a crash, can you share the log file is the logs folder?

And maybe run the app from a terminal to see if it prints anything when it would closes, if so share a screenshot to me.

**Comment by fabiovieitas** [comment]
Good afternoon. It's back to normal. I thank!!!!

**Comment by Tom60chat** [comment]
Something tells me it's not going to be normal for that long.

**Comment by fabiovieitas** [comment]
[2023-01-27 08.35.51.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10518711/2023-01-27.08.35.51.txt)


Good Morning!

It closed again.

**Comment by Tom60chat** [comment]
Hello, I have forgot this issue.

I may have solve the issue after cleaning up the Bing class.
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/commit/789912f554dc34ec16488522aec1e5a3a1f690a0

So I invite you to test version 0.10 when he will be released.

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Tom60chat** [comment]
For cleaning reasons, I will close this issue now, do not hesitate to reopen if the same issue comes back.
