### ISSUE TITLE
[Exception] x: Farmer System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by HeatPhoenix** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#74]
**Describe the bug**
A "crash" of each farmer in my set of accounts with the error
 ```
[Exception] 3: Farmer
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

Attached is the log file.
[2023-02-08 18.12.21.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10688220/2023-02-08.18.12.21.txt)

All my accounts are doing this, with no obvious issue when logging in on the normal page.

**To Reproduce**
I'm on version "0.9.2.0 (latest version)" 

**Additional context**
When logging into the rewards.bing.com on these accounts, no issue occurs.

Many thanks for your fantastic work on the application, by the way.

**Comment by Tom60chat** [comment]
Version 0.9.3 is available (I know it's written" latest" version but that a bug too)

**Comment by HeatPhoenix** [comment]
@Tom60chat Seems  to have solved the issue (whatever may have caused it)!
