### ISSUE TITLE
Bing search farming does not earn points

### ISSUE THREAD

**Issue by danding-s** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#80]
everything was fine yesterday。

**Comment by pan8664716** [comment]
Hello, I have encountered a similar problem. My problem is that moblie point cannot gain ；

My solution is to download the code and replace the desktop_user_agent and mobile_user_agent；

**Comment by danding-s** [comment]
@pan8664716 
can you share your solution

**Comment by pan8664716** [comment]
I replace  the desktop_user_agent  ：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
and rellace the mobile_user_agent ：Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/109.0.1518.72 Version/16.0

**Comment by danding-s** [comment]
understand ,but where do i find the files to replace

**Comment by 12189108** [comment]
MicrosoftRewards-Farmer/TheFarm/Bing.cs

**Comment by Tom60chat** [comment]
Hello, thanks for your feedback.
I will investigate.

@pan8664716 Thanks for your solution, I will test it.

**Comment by Re-hd** [comment]
问一下更新什么时候能发布？我现在已经无法用Rewards Farmer来刷积分了

**Comment by Tom60chat** [comment]
@Re-hd one day, I don't know.

**Comment by Re-hd** [comment]
......好吧

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Re-hd** [comment]
Oh, that's great. My problem has been solved。
thanks.
