### ISSUE TITLE
When finishing card tasks, an error occurred

### ISSUE THREAD

**Issue by shiquda** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#81]
**Describe the bug**
When finishing card tasks, an error occurred.
```
[Exception] Farmer - Evaluation failed: ReferenceError: _w is not
defined
    at __puppeteer_evaluation_script__:1:10
```

**Screenshots**

**Additional context**
it was my first time to use this program and it broke down when it tried to finish card tasks.  

the following is my first-time error log.

[2023-02-19 09.00.26.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10775495/2023-02-19.09.00.26.txt)

**Comment by Tom60chat** [comment]
Dup of #70
