### ISSUE TITLE
The argument "-b/--batch" didn't work properly

### ISSUE THREAD

**Issue by Yuanlailai** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#82]
Batch: -b, --batch
Run program in batch mode, i.e. without any prompt or wait for pressing enter key.

I started the program in cmd with the argument "--batch" like #23. But I still need to "press any key to exit".
version 0.9.3/0.9.2

**Comment by Yuanlailai** [comment]
![image](https://user-images.githubusercontent.com/46029173/220009374-c5bd1c4d-f93c-4807-8765-bcd82276e596.png)
![image](https://user-images.githubusercontent.com/46029173/220012301-1c6e4ea8-05de-42e3-bb7b-1debc56eb451.png)

**Comment by Tom60chat** [comment]
Please use last version.

#50
