### ISSUE TITLE
Evaluation failed: ReferenceError: _w is not defined at __puppeteer_evaluation_script__:1:10

### ISSUE THREAD

**Issue by Ayumi08** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#84]
Tried to make it work, put it all the things correctly, it was able to take how many point i currently have but when it "gets cards" i have an error and it shuts off

Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10

**Comment by Tom60chat** [comment]
Dup of #55
