### ISSUE TITLE
Farmer closes itself

### ISSUE THREAD

**Issue by demiryuca** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#87]
Hello, I used the farmer in no headless to see whats going on and just saw it closed itself telling the error below

[Exception] Farmer - waiting for selector 'div[class="points
clearfix"]' failed: timeout 30000 ms exceeded

Is there a 30000 ms limit because I need to run the whole script again and again when this happens. Hope you can fix it, thanks.

**Comment by Tom60chat** [comment]
Hello, What version was it on?

**Comment by demiryuca** [comment]
v9.2.0
