### ISSUE TITLE
V0.10.0 Profils crashing

### ISSUE THREAD

**Issue by demiryuca** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#90]
In V0.10.0, program runs properly when deleting Profils folder then running but otherwise (With Profils remaining) it's stuck in the sign-in and then crashes with timeout.

Probably not implemented completely yet.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/52105261/221404968-a6fb5f52-6205-40bf-a707-da8044acd96b.png">

**Comment by Tom60chat** [comment]
Hello,

I close this issue because the error occurred on a development version, please reopen it if it still occurs on the release version.
