### ISSUE TITLE
V0.10.0 Program closes itself after completing searches

### ISSUE THREAD

**Issue by demiryuca** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#91]
After the searches are done, program closes itself without letting seeing the gains (cant see the gains as well because cannot obtain the current points on the account (the points text is not appearing or program cant see it) )

**Comment by Tom60chat** [comment]
Hello,

I close this issue because the error occurred on a development version, please reopen it if it still occurs on the release version.
