### ISSUE TITLE
[Exception] Farmer - Execution context was destroyed, most likely because of a navigation.  

### ISSUE THREAD

**Issue by MythicalTrashcan** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#95]
**Describe the bug**
Seems something is wrong when it tries to find something I think.

**To Reproduce**
It just randomly happens ._.

**Expected behavior**
It finishes all tasks and then days done.

**Screenshots**
It is in the title.

**Additional context**
I am running the exe in the debug folder.

Add the latest log file inside the Logs folder inside the app folder.
It didn't generate a file. The last file is 9 days old.

**Comment by Tom60chat** [comment]
You just compiled the current version from the repo, didn't you?

**Comment by MythicalTrashcan** [comment]
> You just compiled the current version from the repo, didn't you?

Yes. I made no changes to anything else.

**Comment by Tom60chat** [comment]
That normal is that doesn't work, you have compiled a dev version that is not stable.

**Comment by MythicalTrashcan** [comment]
> That normal is that doesn't work, you have compiled a dev version that is not stable.

I used the latest download and went to debug > net6.0 > win-x64 > Microsoft Rewards Farmer.exe
Was that unstable?

**Comment by Tom60chat** [comment]
The dev-version in unstable and you should not use it, except if your are contributing or want to test it.

**Comment by MythicalTrashcan** [comment]
Dev and Release still give this error sometimes. It doesn't seem to be just dev.

**Comment by Tom60chat** [comment]
@MythicalTrashcan it's because this exeption it's too general.

He can just be the user that have close chrome or chrome have crashed, puppetter have lost connection to chrome, etc...

**Comment by Tom60chat** [comment]
Hello,

I close this issue because the error occurred on a development version, please reopen it if it still occurs on the release version.

**Comment by yukiryo** [comment]
the same issue
