### ISSUE TITLE
GitHub Updater - API rate error

### ISSUE THREAD

**Issue by Shree7888** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#96]
how to fix api limit error

**Comment by Tom60chat** [comment]
![Error Screenshot](https://media.discordapp.net/attachments/1082185662033317918/1082185662452740238/Screenshot_2023-03-06_114806.png)

**Comment by Tom60chat** [comment]
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/pull/86

**Comment by Tom60chat** [comment]
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/commit/500ac64da8778421369b7334f50d81e2850c1999

**Comment by Tom60chat** [comment]
Hello.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Tom60chat** [comment]
For cleaning reasons, I will close this issue now, do not hesitate to reopen if the same issue comes back.
