### ISSUE TITLE
v0.9.3-beta1

### ISSUE THREAD

**Issue by Checkra2n** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#99]
system: win10 x64
I  use  VPN（clash Tun mode），it prompts error:
 [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
   at __puppeteer_evaluation_script__:1:10ion] Farmer - Evaluation failed: ReferenceError: _w is not
defined
 at __puppeteer_evaluation_script__:1:10] Farmer - Evaluation failed: ReferenceError: _w is not
defined
[](url)

**Comment by Checkra2n** [comment]
https://imgloc.com/i/o2RKH

**Comment by Tom60chat** [comment]
Duplicate of #55
